dist: xenial

language: java

notifications:
  email:
    on_success: change
    on_failure: always

jdk:
 - openjdk8
 
cache:
  directories:
  - $HOME/.m2
 
install: false
 
script: 
- mvn clean test -P errorprone
